name: Pull request validation

on:
  pull_request:

  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        npm-version: [default, latest]

    steps:
      - name: Checking out for ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install latest NPM
        if: ${{ matrix.npm-version == 'latest' }}
        run: npm install -g npm

      - run: |
          npm install
          npm run prepublishOnly
          npm pack

      - uses: actions/upload-artifact@v2
        if: ${{ matrix.node-version == '16.x' }}
        with:
          name: e2e-tests
          path: '__e2e__/**/*'

      - uses: actions/upload-artifact@v2
        if: ${{ matrix.node-version == '16.x' }}
        with:
          name: package
          path: '*.tgz'

  test:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        resolver:
          - commonjs
          - esbuild
          - esm
          - rollup
          - webpack4-commonjs
          - webpack4-esm
          - webpack5-commonjs
          - webpack5-esm
        node-version: [14.x, 16.x]
        npm-version: [default, latest]

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: e2e-tests

      - uses: actions/download-artifact@v2
        with:
          name: package

      - name: Build test image
        run: |
          cd node-${{ matrix.node-version }}-${{ matrix.resolver }}
          cp ../*.tgz .
          ls -la
          docker build --build-arg NPM_VERSION=${{ matrix.npm-version }} --file Dockerfile --tag test-image .

      - name: Run test
        run: |
          cd node-${{ matrix.node-version }}-${{ matrix.resolver }}
          docker run --name test-container test-image > actual.txt
          diff expected.txt actual.txt
