# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Manually triggered test

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        default: 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Checking out for ${{ github.ref }}
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: |
          npm install
          npm run build
          npm pack

      - uses: actions/upload-artifact@v2
        if: ${{ matrix.node-version == '16.x' }}
        with:
          name: e2e-test
          path: '__e2e__/__tests__/**/*'

      - uses: actions/upload-artifact@v2
        if: ${{ matrix.node-version == '16.x' }}
        with:
          name: package
          path: '*.tgz'

  test:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: actions/download-artifact@v2
        with:
          name: e2e-tests

      - uses: actions/download-artifact@v2
        with:
          name: package

      - name: Build test image
        run: |
          cd e2e-tests/node
          docker build --tag test-image .

      - name: Run test
        run: |
          docker run --name test-container test-image
          docker cp test-image:/var/test/expected.txt .
          diff expected.txt actual.txt
